// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFn1EyRkZMM-FWoiAcvxvRu0ki0xFXx58',
    appId: '1:559381224141:web:f1602524c683bdc9b5e784',
    messagingSenderId: '559381224141',
    projectId: 'virtualfashionassistant-3fcb8',
    authDomain: 'virtualfashionassistant-3fcb8.firebaseapp.com',
    storageBucket: 'virtualfashionassistant-3fcb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzJP30s88C9Hmplf7QYHRvd6bwWYCiUA',
    appId: '1:559381224141:android:3411670b95c9d644b5e784',
    messagingSenderId: '559381224141',
    projectId: 'virtualfashionassistant-3fcb8',
    storageBucket: 'virtualfashionassistant-3fcb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HBtI5CkUnJNX_Pex-v_1eRPCJFb5uUw',
    appId: '1:559381224141:ios:225ebd6fe711060eb5e784',
    messagingSenderId: '559381224141',
    projectId: 'virtualfashionassistant-3fcb8',
    storageBucket: 'virtualfashionassistant-3fcb8.firebasestorage.app',
    iosBundleId: 'com.example.minimalecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3HBtI5CkUnJNX_Pex-v_1eRPCJFb5uUw',
    appId: '1:559381224141:ios:225ebd6fe711060eb5e784',
    messagingSenderId: '559381224141',
    projectId: 'virtualfashionassistant-3fcb8',
    storageBucket: 'virtualfashionassistant-3fcb8.firebasestorage.app',
    iosBundleId: 'com.example.minimalecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFn1EyRkZMM-FWoiAcvxvRu0ki0xFXx58',
    appId: '1:559381224141:web:7a164c3e933142b5b5e784',
    messagingSenderId: '559381224141',
    projectId: 'virtualfashionassistant-3fcb8',
    authDomain: 'virtualfashionassistant-3fcb8.firebaseapp.com',
    storageBucket: 'virtualfashionassistant-3fcb8.firebasestorage.app',
  );
}
